const wordList = [
    { word: "spiderman", hint: "A superhero with spider-like abilities, known for his agility and web-slinging." },
    { word: "ironman", hint: "A billionaire inventor and philanthropist who fights crime using a powered suit of armor." },
    { word: "captainamerica", hint: "A patriotic super soldier with enhanced strength, agility, and a shield." },
    { word: "thor", hint: "A Norse god of thunder who wields a magical hammer named Mjolnir." },
    { word: "hulk", hint: "A scientist who transforms into a green-skinned behemoth with immense strength when enraged." },
    { word: "blackwidow", hint: "A highly trained spy and assassin with exceptional martial arts skills." },
    { word: "doctorstrange", hint: "A former neurosurgeon who becomes the Sorcerer Supreme, mastering the mystic arts." },
    { word: "wolverine", hint: "A mutant with retractable claws, accelerated healing, and heightened senses." },
    { word: "blackpanther", hint: "The king of the fictional African nation of Wakanda, possessing enhanced strength and agility." },
    { word: "captainmarvel", hint: "A former Air Force pilot imbued with superhuman strength, endurance, and flight." },
    { word: "thanos", hint: "A powerful cosmic warlord obsessed with obtaining the Infinity Stones to achieve ultimate power." },
    { word: "loki", hint: "The adopted brother of Thor, known for his mischief and manipulation." },
    { word: "scarletwitch", hint: "A mutant with reality-warping abilities and mastery over chaos magic." },
    { word: "vision", hint: "An android created by Ultron, possessing superhuman strength, density manipulation, and energy projection." },
    { word: "groot", hint: "A sentient tree-like creature with the ability to regenerate and control plant matter." },
    { word: "rocket", hint: "A genetically modified raccoon with expertise in weapons and technology." },
    { word: "gamora", hint: "An orphaned alien raised by Thanos, skilled in combat and assassination." },
    { word: "drax", hint: "A vengeful warrior seeking to destroy Thanos, possessing superhuman strength and durability." },
    { word: "starlord", hint: "The leader of the Guardians of the Galaxy, known for his piloting skills and sense of humor." },
    { word: "antman", hint: "A former thief who can shrink to the size of an ant and communicate with insects." },
    { word: "hawkeye", hint: "A master archer and skilled marksman, known for his accuracy and precision." },
    { word: "falcon", hint: "An Air Force veteran equipped with a winged jetpack, trained in aerial combat." },
    { word: "wintersoldier", hint: "A former brainwashed assassin with enhanced strength, agility, and combat skills." },
    { word: "nickfury", hint: "The director of S.H.I.E.L.D., known for his strategic mind and ability to assemble heroes." },
    { word: "agentcoulson", hint: "A loyal agent of S.H.I.E.L.D., dedicated to protecting the world from supernatural threats." },
    { word: "mysterio", hint: "A master illusionist and manipulator, known for his use of special effects and deception." },
    { word: "redskull", hint: "A Nazi agent and archenemy of Captain America, known for his ruthless ambition and hatred." },
    { word: "magneto", hint: "A mutant with the ability to generate and control magnetic fields, advocating for mutant supremacy." },
    { word: "professorx", hint: "The founder of the X-Men, possessing powerful psychic abilities and a vision for mutant-human coexistence." },
    { word: "storm", hint: "A mutant with the ability to manipulate weather patterns and atmospheric phenomena." },
    { word: "rogue", hint: "A mutant with the ability to absorb the powers and memories of others through physical contact." },
    { word: "deadpool", hint: "A wisecracking mercenary with accelerated healing, known for breaking the fourth wall." }
];
